# Functions in Python 

In [4]:
#A function that takes a string as input and returns the number of vowels in the string
str1 = input("Enter a string:    ")


count=0  # Initializing count variable

i=0

for i in range (len(str1)):
    if (
        (str1[i] == "a")
        or (str1[i] == "e")
        or (str1[i] == "i")
        or (str1[i] == "o")
        or (str1[i] == "u")
    ):
        count += 1
print("The total number of vowels in string is:", count)        

Enter a string:    Hi my name is Gaurav
The total number of vowels in string is: 7


In [36]:
# A function that checks if a given number is prime or not

n = int(input("Enter any Number: "))
                                     # To check if the number is greater than 1
if n > 1:  
    for i in range(2, int(n/2)+1):
        if (n % i) == 0:
            print(n, "is not a prime number")
        break
    else:
        print(n, "is a prime number")
                                     # If the number is less than 1, its also not a prime number.
else:
    print(n, "is not a prime number")
        

Enter any Number: 3
3 is a prime number


In [40]:
# A function that takes a list of numbers as input and returns the sum of all the even numbers in the list.

nums = []
print("Enter the elements for the list: ")
for i in range(5):
    val = int(input())
    nums.append(val)

sum = 0

for i in range(5):
    if nums[i]%2 == 0:
        sum = sum + nums[i]

print("\nSum of Even Numbers is", sum)

Enter the elements for the list: 
12345
13245
1245
155612
151

Sum of Even Numbers is 155612


In [45]:
# A function that takes two strings as input and checks if they are anagrams of each other
I1 = input()
I2 = input()

def Anagram_check(I1, I2):  
                                    # Strings are sorted and check whether both are matching or not  
    if(sorted(I1)== sorted(I2)):  
        print("Both strings are an Anagram.")  
    else:  
        print("Both strings are not an Anagram.")  
         
print( "String value1 : ", I1 )  
print( "String value2 : ", I2 )  
Anagram_check(I1, I2) 

bat
rat
String value1 :  bat
String value2 :  rat
Both strings are not an Anagram.


In [56]:
#A function that takes a list of integers as input and returns a new list with only the unique elements in the original list.
N= input()

def get_unique_numbers(N):

    list_of_unique_numbers = []

    unique_numbers = set(N)

    for N in unique_numbers:
        list_of_unique_numbers.append(N)

    return list_of_unique_numbers


print(get_unique_numbers(N))

12345655
['1', '3', '4', '2', '6', '5']


In [57]:
# A function that reverses a given string without using the reverse() function or slicing.
string=input()
str=""
for i in string:
    str=i+str
print("Reversed string:",str)

Gaurav Gavali
Reversed string: ilavaG varuaG


In [83]:
# A function that takes a list of words as input and returns the longest word in the list
a= input().split(",")
def longestLength(words):
    finalList = []
     
    for word in words:
        finalList.append((len(word), word))
     
    finalList.sort()
     
    print("The word with the longest length is:", finalList[-1][1])

longestLength(a)

cat,mother,battery,documentation
The word with the longest length is: documentation


In [84]:
#A function that calculates the factorial of a given number using recursion.

def recur_factorial(n):
    if n == 1:
        return n
    else:
        return n*recur_factorial(n-1)

num = int(input())
                                                  #To check if the number is negative
if num < 0:
    print("Sorry, factorial does not exist for negative numbers")
elif num == 0:
    print("The factorial of 0 is 1")
else:
    print("The factorial of", num, "is", recur_factorial(num))


5
The factorial of 5 is 120


In [87]:
#A function that takes a list of strings as input and returns a new list with the strings sorted in alphabetical order
str2 = input().split()
str2.sort()
print(str2)

xerox gaurav place car
['car', 'gaurav', 'place', 'xerox']


In [95]:
# A function that takes a dictionary as input and returns a new dictionary where the keys and values are swapped
dict = {}

for i in range(3):
    name = input("Enter employee's name: ")
    salary = input("Enter employee's salary: ")

    dict[name] = salary
new_dict = {value:key for key, value in dict.items()}
print(dict)
print(new_dict)


Enter employee's name: Gaurav
Enter employee's salary: 100
Enter employee's name: Pratik
Enter employee's salary: 200
Enter employee's name: Prafulla
Enter employee's salary: 500
{'Gaurav': '100', 'Pratik': '200', 'Prafulla': '500'}
{'100': 'Gaurav', '200': 'Pratik', '500': 'Prafulla'}


# Numpy & Function 

In [101]:

import numpy as np

# A NumPy program to find the most frequent value in an array
x = np.array([1,2,3,4,5,1,2,1,1,1])
print("Original array:")
print(x)

print("Most frequent value in the above array:")
print(np.bincount(x).argmax())


Original array:
[1 2 3 4 5 1 2 1 1 1]
Most frequent value in the above array:
1


In [103]:
#Given a 2D NumPy array, write a program to find the sum of each row and each column
a = np.matrix('10 20; 30 40')
print("matrix: \n", a)

sum_of_rows = np.sum(a, axis = 0)
print("\nSum of all the rows: ", sum_of_rows)

sum_of_cols = np.sum(a, axis = 1)
print("\nSum of all the columns: \n", sum_of_cols)

matrix: 
 [[10 20]
 [30 40]]

Sum of all the rows:  [[40 60]]

Sum of all the columns: 
 [[30]
 [70]]


In [104]:
from sklearn import preprocessing as pre

# A function to normalize a given 1D NumPy array such that the values range between 0 and 1
x = np.array([13, 16, 19, 22, 23, 38, 47, 56, 58, 63, 65, 70, 71])
#reshape array so that it works with sklearn
x = x.reshape(-1, 1)
#normalize all values to be between 0 and 1
x_norm = pre.MinMaxScaler().fit_transform(x)

#view normalized array
print(x_norm)

[[0.        ]
 [0.05172414]
 [0.10344828]
 [0.15517241]
 [0.17241379]
 [0.43103448]
 [0.5862069 ]
 [0.74137931]
 [0.77586207]
 [0.86206897]
 [0.89655172]
 [0.98275862]
 [1.        ]]


In [105]:
# A program to calculate the Euclidean distance between two points represented as NumPy arrays.
ary1 = np.array((1, 2, 3))
ary2 = np.array((1, 1, 1))
 
# calculating Euclidean distance

dist = np.linalg.norm(ary1 - ary2)    # using linalg.norm()
 
# printing Euclidean distance
print(dist)

2.23606797749979


In [106]:
#Given two 1D NumPy arrays, write a program to find the common elements between them.
arr1 = np.array([1, 3, 4, 3])
arr2 = np.array([3, 1, 2, 1])

result = np.intersect1d(arr1, arr2)

print("The common elements are:", result)

The common elements are: [1 3]


In [112]:
# Implement a function to compute the moving average of a 1D NumPy array with a specified window size.
# Program to calculate moving average

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
window_size = 3

def moving_average(arr, window_size):
    cumsum = np.cumsum(arr, dtype=float)
    cumsum[window_size:] = cumsum[window_size:] - cumsum[:-window_size]
    return cumsum[window_size - 1:] / window_size

result = moving_average(arr, window_size)
print(result)

[2. 3. 4. 5. 6. 7. 8. 9.]


In [115]:
# A NumPy program to find the k smallest values in a given array
array1 = np.array([1, 7, 8, 2, 0.1, 3, 15, 2.5])
print(array1)
k = 3
result = np.argpartition(array1, k)
print("\nk smallest values:")
print(array1[result[:k]])

[ 1.   7.   8.   2.   0.1  3.  15.   2.5]

k smallest values:
[0.1 1.  2. ]


In [116]:
# A function to calculate the cross-correlation between two 1D NumPy arrays
# Creating two numpy arrays
arry1 = np.array([1,2,3])
arry2 = np.array([4,5,6])

print("Original array 1:\n",arry1,"\n")
print("Original array 2:\n",arry2,"\n")

# Finding cross correlation
res = np.correlate(arry1,arry2)
print("Result:\n",res,"\n")

Original array 1:
 [1 2 3] 

Original array 2:
 [4 5 6] 

Result:
 [32] 



In [120]:
# A 2D NumPy array, write a program to find the row with the maximum sum
# Create a 3x4 matrix
matrix = [[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 10, 11, 12]]
m = 3
n = 4

# Initialize max_sum and max_row to 0
max_sum = 0
max_row = -1

# Traverse the matrix row by row and find the row with maximum sum
for i in range(m):
    row_sum = 0
    for j in range(n):
        row_sum += matrix[i][j]
    if row_sum > max_sum:
        max_sum = row_sum
        max_row = i

# Print the index of the row with maximum sum
print("Row with maximum sum is: ", max_row)


Row with maximum sum is:  2


In [126]:
# A NumPy program to create a random 2D array and extract all the unique rows from it

# Create a 2D numpy array
arr2D = np.array([[11, 11, 12, 11],
                  [13, 11, 12, 11],
                  [16, 11, 12, 11],
                  [11, 11, 12, 11]])

print(arr2D, sep = '\n')

def extract_unique_rows(arr2D):
    uniqueRows = np.unique(arr2D)
    return uniqueRows
extracted= extract_unique_rows(uniqueRows)

print('Unique Rows:', uniqueRows, sep = '\n')


[[11 11 12 11]
 [13 11 12 11]
 [16 11 12 11]
 [11 11 12 11]]
Unique Rows:
[11 12 13 16]


# Pandas & Functions

In [127]:
import pandas as pd

#A Pandas program to calculate the correlation matrix for a given DataFrame

data = {'A': [45, 37, 42, 35, 39],
        'B': [38, 31, 26, 28, 33],
        'C': [10, 15, 17, 21, 12]
        }

df = pd.DataFrame(data)

corr_matrix = df.corr()
print(corr_matrix)

          A         B         C
A  1.000000  0.518457 -0.701886
B  0.518457  1.000000 -0.860941
C -0.701886 -0.860941  1.000000


In [133]:
# A function that finds the top n rows with the largest values in a specific column of a DataFrame
data = {'A': [45, 37, 42, 35, 39],
        'B': [38, 31, 26, 28, 33],
        'C': [10, 15, 17, 21, 12],
        'D': [60, 75, 17, 91, 38]
        }

df = pd.DataFrame(data)
df.nlargest(2,"A")

A   B   C   D
0  45  38  10  60
2  42  26  17  17

In [134]:
# A program to calculate the cumulative sum of a specific column in a DataFrame, grouped by another column
df = pd.DataFrame({'C1' : ['a','a','a','b','b'],
           'C2' : [1,2,3,4,5]})
df['cumsum'] = df.groupby(by=['C1'])['C2'].transform(lambda x: x.cumsum())
df

C1  C2  cumsum
0  a   1       1
1  a   2       3
2  a   3       6
3  b   4       4
4  b   5       9

In [140]:
# A function that calculates the moving average of a specific column in a DataFrame with a given window size

def moving_average(dataframe, column, window_size):
    rolling_avg = dataframe[column].rolling(window=window_size, min_periods=1).mean()
    return rolling_avg

data = {'Name': ['A', 'B', 'C', 'D', 'E'],
        'Value': [10, 20, 30, 40, 50]}
df = pd.DataFrame(data)

column_name = 'Value'
window_size = 3

moving_avg = moving_average(df, column_name, window_size)
print(moving_avg)

0    10.0
1    15.0
2    20.0
3    30.0
4    40.0
Name: Value, dtype: float64


In [144]:
# A Pandas program to find the most common value in each column of a DataFrame
data = {'Name': ['A', 'B', 'C', 'D', 'E', 'F','G'],
        'Value': [10, 20, 50, 30, 50, 40, 50]}
df = pd.DataFrame(data)
df['Value'].mode()


0    50
Name: Value, dtype: int64

In [149]:
# A function that finds the outliers in a specific column of a DataFrame using the Z-score method

def outliers_zscore(dataframe, column, threshold=3):
    z_scores = (dataframe[column] - dataframe[column].mean()) / dataframe[column].std()
    outliers = dataframe[abs(z_scores) > threshold]
    return outliers

data_1 = {'Name': ['A', 'B', 'C', 'D', 'E'],
        'Value': [10, 20, 30, 40, 50]}
df = pd.DataFrame(data_1)

column_name = 'Value'
threshold = 2

outliers = outliers_zscore(df, column_name, threshold)
print("Outliers:")
print(outliers)

Outliers:
Empty DataFrame
Columns: [Name, Value]
Index: []


In [160]:
# A program to find the rows in a DataFrame where a specific column's value is greater than the average value of that column



In [158]:
# A function that performs a left join between two DataFrames based on a common column
data1 = {'Name': ['A', 'B', 'C', 'D', 'E'],
        'Value': [10, 20, 50, 30, 50]}
df1 = pd.DataFrame(data1)

data2 = {'Name': [ 'F','G','H','I','J'],
        'Value': [10, 20, 30, 40, 50]}
df2 = pd.DataFrame(data2)


df3=df1.join(df2, lsuffix="_left", rsuffix="_right")
print(df3)

  Name_left  Value_left Name_right  Value_right
0         A          10          F           10
1         B          20          G           20
2         C          50          H           30
3         D          30          I           40
4         E          50          J           50


In [154]:
# A program to calculate the covariance between two specific columns in a DataFrame
df = pd.DataFrame([[10, 20, 30, 40], [7, 14, 21, 28], [55, 15, 8, 12],
                   [15, 14, 1, 8], [7, 1, 1, 8], [5, 4, 9, 2]],
                  columns=['Apple', 'Orange', 'Banana', 'Pear'],
                  index=['Basket1', 'Basket2', 'Basket3', 'Basket4',
                         'Basket5', 'Basket6'])
 
print("\nCalculating Covariance")
print(df.cov())
 
print("\n Between 2 columns")
# Covariance of Apple vs Orange
print(df.Apple.cov(df.Orange))


Calculating Covariance
        Apple     Orange      Banana        Pear
Apple   367.9  47.600000  -40.200000  -35.000000
Orange   47.6  52.666667   54.333333   77.866667
Banana  -40.2  54.333333  134.266667  154.933333
Pear    -35.0  77.866667  154.933333  211.866667

 Between 2 columns
47.6


In [155]:
# A function that calculates the percentage change of each value in a DataFrame column compared to its previous value.
df = pd.DataFrame({
    '2016': [1769950, 30586265],
    '2015': [1500923, 40912316],
    '2014': [1371819, 41403351]},
    index=['GOOG', 'APPL'])
print(df)
df.pct_change(axis='columns', periods=-1)

          2016      2015      2014
GOOG   1769950   1500923   1371819
APPL  30586265  40912316  41403351


2016      2015  2014
GOOG  0.179241  0.094112   NaN
APPL -0.252395 -0.011860   NaN

In [1]:
######