# Numpy

In [86]:
import numpy as np
import pandas as pd

In [4]:
#NumPy array with values ranging from 1 to 10
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
#NumPy array of size 50 using random values.
NP=np.random.randint(1,100,50)
print(NP)

[60 94 83 87 26 82 86 46 63 84 34  6 43 39 59 63 49 18 67 24 23 89 20 88
 32 65  7 89 41 90 72 98 75 60 70 44 41 60 18 60 79 10  8 98 16  7 30 90
 32 37]


In [27]:
#The mean of a NumPy array
M=np.mean(NP)
print(M)

53.24


In [24]:
#The maximum value in a NumPy array
np.max(NP)

98

In [29]:
STD=np.std(NP)    #Standard Deviation
print(STD)

28.37714573384716


In [31]:
#Normalize a NumPy array by subtracting the mean and dividing by the standard deviation.
Normalize = (NP-M/STD)
print(Normalize)

[58.12384232 92.12384232 81.12384232 85.12384232 24.12384232 80.12384232
 84.12384232 44.12384232 61.12384232 82.12384232 32.12384232  4.12384232
 41.12384232 37.12384232 57.12384232 61.12384232 47.12384232 16.12384232
 65.12384232 22.12384232 21.12384232 87.12384232 18.12384232 86.12384232
 30.12384232 63.12384232  5.12384232 87.12384232 39.12384232 88.12384232
 70.12384232 96.12384232 73.12384232 58.12384232 68.12384232 42.12384232
 39.12384232 58.12384232 16.12384232 58.12384232 77.12384232  8.12384232
  6.12384232 96.12384232 14.12384232  5.12384232 28.12384232 88.12384232
 30.12384232 35.12384232]


In [39]:
#NumPy array of size 6 using random values
NP2=np.random.randint(1,100,6)
print(NP2)

[49 17 93 46 46 76]


In [41]:
#Reshape a 1D NumPy array into a 2D array with 2 rows and 3 columns.
Reshape= np.reshape(NP2, (2,3))
print(Reshape)

[[49 17 93]
 [46 46 76]]


In [43]:
#Two NumPy array of size 10 using random values
A = np.random.randint(1,100,10)
print(A)
B = np.random.randint(1,100,10)
print(B)

[99 28 55 56  6 79 97 73 49 55]
[51 65 69 20 71 22 29 97 76 45]


In [45]:
#The dot product of two NumPy arrays
np.dot(A,B)

30041

In [52]:
#NumPy array of size 50 using random values ranging from (0, 5)
I=np.random.randint(0,5,50)
print(I)

[2 2 3 0 4 3 1 0 0 1 4 4 1 1 4 3 4 3 1 2 3 3 0 3 1 3 0 1 0 1 4 1 0 2 3 3 3
 3 4 2 2 0 3 3 0 0 4 4 0 2]


In [59]:
#The indices of the non-zero elements in a NumPy array.
Indices= np.nonzero(I)
print(Indices)

(array([ 0,  1,  2,  4,  5,  6,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 23, 24, 25, 27, 29, 30, 31, 33, 34, 35, 36, 37, 38, 39, 40,
       42, 43, 46, 47, 49], dtype=int64),)


In [61]:
#NumPy array of size 20 using random values 
NP3= np.random.randint(0,5,50)
print(NP3)
NP4= np.random.randint(0,5,50)
print(NP4)

[1 1 2 2 0 2 2 1 1 1 1 0 4 0 3 0 1 4 4 1 2 4 3 1 1 1 2 4 4 0 4 4 2 2 3 1 4
 3 4 2 3 1 3 0 4 3 0 0 0 0]
[2 3 3 1 3 0 3 1 4 4 0 0 0 0 0 3 4 3 0 3 3 1 4 0 2 1 0 0 3 4 1 2 0 3 4 3 4
 1 2 0 1 1 4 1 2 2 4 3 3 3]


In [62]:
#The element-wise product of two NumPy arrays.
np.multiply(NP3,NP4)

array([ 2,  3,  6,  2,  0,  0,  6,  1,  4,  4,  0,  0,  0,  0,  0,  0,  4,
       12,  0,  3,  6,  4, 12,  0,  2,  1,  0,  0, 12,  0,  4,  8,  0,  6,
       12,  3, 16,  3,  8,  0,  3,  1, 12,  0,  8,  6,  0,  0,  0,  0])

In [65]:
#A random NumPy array with 10 elements.
NP5 = np.random.random(10)
print(NP5)

[0.89764416 0.63221923 0.97556658 0.34420686 0.07767147 0.65025154
 0.71625292 0.29976319 0.65695996 0.2968107 ]


In [68]:
#Two NumPy array of size 15 using random values 
NP6= np.random.randint(0,100,15)
print(NP6)
NP7= np.random.randint(0,100,15)
print(NP7)

[86 56 49 14 93 97 39 44 23 76 26 71 44 82 33]
[36 32 78 50 59 23 52 58 48 81  6 48 26 37 99]


In [70]:
Stack=np.vstack((NP6,NP7))
print(Stack)

[[86 56 49 14 93 97 39 44 23 76 26 71 44 82 33]
 [36 32 78 50 59 23 52 58 48 81  6 48 26 37 99]]


In [71]:
#Create a 2D NumPy array of size 3x6 using random values 
NP8 = np.random.randint(5, size=(3,6))
print(NP8)

[[3 0 2 3 3 2]
 [2 0 3 1 3 2]
 [1 2 2 0 3 3]]


In [72]:
#Transpose a 2D NumPy array.
np.transpose(NP8)

array([[3, 2, 1],
       [0, 0, 2],
       [2, 3, 2],
       [3, 1, 0],
       [3, 3, 3],
       [2, 2, 3]])

In [77]:
#Create a 2D NumPy array of size 2x2 using random values 
NP9 = np.random.randint(5, size=(2,2))
print(NP9)

[[1 2]
 [2 4]]


In [75]:
#Determinant
np.linalg.det(NP9)

2.0

In [78]:
#NumPy array of size 30 using random values 
NP10= np.random.randint(0,100,30)
print(NP10)

[15 34 82 53 86 73 71 81 74 49  9 61 93 75 97 93 24 49 46 89 13 63 44 14
 51 24 75  3 63 44]


In [79]:
#Ascending order
np.sort(NP10)

array([ 3,  9, 13, 14, 15, 24, 24, 34, 44, 44, 46, 49, 49, 51, 53, 61, 63,
       63, 71, 73, 74, 75, 75, 81, 82, 86, 89, 93, 93, 97])

In [80]:
#NumPy array of size 25 using random values 
NP11= np.random.randint(0,100,25)
print(NP11)

[73 87 74 44 80 68 97 60 26 63  5  2 78 62 81 28 40 27 14 48 98 85  7 74
 18]


In [82]:
#Extract all odd numbers from a NumPy array
NP11[NP11 % 2 == 1]

array([73, 87, 97, 63,  5, 81, 27, 85,  7])

In [83]:
#Two NumPy array of size 3x4 and 4x2 using random values 
NP12 = np.random.randint(10, size=(3,4))
print(NP12)
NP13 = np.random.randint(10, size=(4,2))
print(NP13)

[[0 3 6 7]
 [9 7 0 0]
 [6 5 9 7]]
[[2 8]
 [7 6]
 [1 9]
 [0 3]]


In [84]:
#matrix multiplication between a 3x4 and a 4x2 NumPy array.
np.dot(NP12,NP13)

array([[ 27,  93],
       [ 67, 114],
       [ 56, 180]])

# Pandas

In [90]:
Cars = pd.read_csv(r'C:/Users/Lenovo/Downloads/cars.csv')
print(Cars)

                      Car Name   MPG  Cylinders  Displacement  Horsepower  \
0    Chevrolet Chevelle Malibu  18.0        8.0         307.0       130.0   
1            Buick Skylark 320  15.0        8.0         350.0       165.0   
2           Plymouth Satellite  18.0        8.0         318.0       150.0   
3                AMC Rebel SST  16.0        8.0         304.0       150.0   
4                  Ford Torino  17.0        8.0         302.0       140.0   
..                         ...   ...        ...           ...         ...   
404            Ford Mustang GL  27.0        4.0         140.0        86.0   
405          Volkswagen Pickup  44.0        4.0          97.0        52.0   
406              Dodge Rampage  32.0        4.0         135.0        84.0   
407                Ford Ranger  28.0        4.0         120.0        79.0   
408                 Chevy S-10  31.0        4.0         119.0        82.0   

     Weight  Acceleration  Model  Origin  
0    3504.0          12.0   70.0

In [94]:
#2.	Display the first 5 rows of a DataFrame
Cars[:5]

Car Name   MPG  Cylinders  Displacement  Horsepower  \
0  Chevrolet Chevelle Malibu  18.0        8.0         307.0       130.0   
1          Buick Skylark 320  15.0        8.0         350.0       165.0   
2         Plymouth Satellite  18.0        8.0         318.0       150.0   
3              AMC Rebel SST  16.0        8.0         304.0       150.0   
4                Ford Torino  17.0        8.0         302.0       140.0   

   Weight  Acceleration  Model Origin  
0  3504.0          12.0   70.0     US  
1  3693.0          11.5   70.0     US  
2  3436.0          11.0   70.0     US  
3  3433.0          12.0   70.0     US  
4  3449.0          10.5   70.0     US

In [95]:
#Count the number of missing values in each column of a DataFrame
Cars.isna().sum().sum()

10

In [104]:
#Filter a DataFrame to only include rows where a specific column meets a certain condition.
Cars1=Cars[Cars["Origin"] == 'US'] 
print(Cars1)

                      Car Name   MPG  Cylinders  Displacement  Horsepower  \
0    Chevrolet Chevelle Malibu  18.0        8.0         307.0       130.0   
1            Buick Skylark 320  15.0        8.0         350.0       165.0   
2           Plymouth Satellite  18.0        8.0         318.0       150.0   
3                AMC Rebel SST  16.0        8.0         304.0       150.0   
4                  Ford Torino  17.0        8.0         302.0       140.0   
..                         ...   ...        ...           ...         ...   
403           Chevrolet Camaro  27.0        4.0         151.0        90.0   
404            Ford Mustang GL  27.0        4.0         140.0        86.0   
406              Dodge Rampage  32.0        4.0         135.0        84.0   
407                Ford Ranger  28.0        4.0         120.0        79.0   
408                 Chevy S-10  31.0        4.0         119.0        82.0   

     Weight  Acceleration  Model Origin  
0    3504.0          12.0   70.0 

In [105]:
Cars2=Cars1[Cars1["MPG"] > 0] 
print(Cars2)

                      Car Name   MPG  Cylinders  Displacement  Horsepower  \
0    Chevrolet Chevelle Malibu  18.0        8.0         307.0       130.0   
1            Buick Skylark 320  15.0        8.0         350.0       165.0   
2           Plymouth Satellite  18.0        8.0         318.0       150.0   
3                AMC Rebel SST  16.0        8.0         304.0       150.0   
4                  Ford Torino  17.0        8.0         302.0       140.0   
..                         ...   ...        ...           ...         ...   
403           Chevrolet Camaro  27.0        4.0         151.0        90.0   
404            Ford Mustang GL  27.0        4.0         140.0        86.0   
406              Dodge Rampage  32.0        4.0         135.0        84.0   
407                Ford Ranger  28.0        4.0         120.0        79.0   
408                 Chevy S-10  31.0        4.0         119.0        82.0   

     Weight  Acceleration  Model Origin  
0    3504.0          12.0   70.0 

In [106]:
Cars3=Cars2[Cars2["Horsepower"] > 150] 
print(Cars3)

                            Car Name   MPG  Cylinders  Displacement  \
1                  Buick Skylark 320  15.0        8.0         350.0   
5                   Ford Galaxie 500  15.0        8.0         429.0   
6                   Chevrolet Impala  14.0        8.0         454.0   
7                  Plymouth Fury iii  14.0        8.0         440.0   
8                   Pontiac Catalina  14.0        8.0         455.0   
9                 AMC Ambassador DPL  15.0        8.0         390.0   
18               Dodge Challenger SE  15.0        8.0         383.0   
19                Plymouth 'Cuda 340  14.0        8.0         340.0   
22           Buick Estate Wagon (sw)  14.0        8.0         455.0   
34                         Ford F250  10.0        8.0         360.0   
35                         Chevy C20  10.0        8.0         307.0   
36                        Dodge D200  11.0        8.0         318.0   
37                          Hi 1200D   9.0        8.0         304.0   
49    

In [107]:
#Group a DataFrame by a specific column and calculate the average value for each group.
Cars.groupby('Origin')['Cylinders'].mean()

Origin
Europe    4.150685
Japan     4.102564
US        6.290196
Name: Cylinders, dtype: float64

In [111]:
#Sort a DataFrame based on values in a specific column
Cars.sort_values("Car Name")

Car Name   MPG  Cylinders  Displacement  Horsepower  \
106  AMC Ambassador Brougham  13.0        8.0         360.0       175.0   
9         AMC Ambassador DPL  15.0        8.0         390.0       190.0   
76        AMC Ambassador SST  17.0        8.0         304.0       150.0   
267              AMC Concord  19.4        6.0         232.0        90.0   
325              AMC Concord  24.3        4.0         151.0        90.0   
..                       ...   ...        ...           ...         ...   
86           Volvo 145e (sw)  18.0        4.0         121.0       112.0   
189              Volvo 244DL  22.0        4.0         121.0        98.0   
217                Volvo 245  20.0        4.0         130.0       102.0   
285              Volvo 264gl  17.0        6.0         163.0       125.0   
371             Volvo Diesel  30.7        6.0         145.0        76.0   

     Weight  Acceleration  Model  Origin  
106  3821.0          11.0   73.0      US  
9    3850.0           8.5   70.0      US  
76   3672.0          11.5   72.0      US  
267  3210.0          17.2   78.0      US  
325  3003.0          20.1   80.0      US  
..      ...           ...    ...     ...  
86      NaN          14.5   72.0  Europe  
189  2945.0          14.5   75.0  Europe  
217  3150.0          15.7   76.0  Europe  
285  3140.0          13.6   78.0  Europe  
371  3160.0          19.6   81.0  Europe  

[409 rows x 9 columns]

In [113]:
def categorize_weight(Weight):
    if Weight < 1500:
        return 'Low Weight'
    elif Weight < 3000:
        return 'Medium Weight'
    else:
        return 'High Weight'
Cars[' Based on Weight '] = Cars['Weight'].apply(categorize_weight)
print(Cars)

                      Car Name   MPG  Cylinders  Displacement  Horsepower  \
0    Chevrolet Chevelle Malibu  18.0        8.0         307.0       130.0   
1            Buick Skylark 320  15.0        8.0         350.0       165.0   
2           Plymouth Satellite  18.0        8.0         318.0       150.0   
3                AMC Rebel SST  16.0        8.0         304.0       150.0   
4                  Ford Torino  17.0        8.0         302.0       140.0   
..                         ...   ...        ...           ...         ...   
404            Ford Mustang GL  27.0        4.0         140.0        86.0   
405          Volkswagen Pickup  44.0        4.0          97.0        52.0   
406              Dodge Rampage  32.0        4.0         135.0        84.0   
407                Ford Ranger  28.0        4.0         120.0        79.0   
408                 Chevy S-10  31.0        4.0         119.0        82.0   

     Weight  Acceleration  Model  Origin  Based on Weight   
0    3504.0   

In [128]:
#A new column in a DataFrame based on values from existing columns
def categorize_weight(Weight):
    if Weight < 1500:
        return 'Low Weight'
    if 1500 <= Weight < 3000:
        return 'Medium Weight'
    else: 
        return 'High Weight'
Cars[' Based on Weight '] = Cars['Weight'].apply(categorize_weight)
print(Cars)

                      Car Name   MPG  Cylinders  Displacement  Horsepower  \
0    Chevrolet Chevelle Malibu  18.0        8.0         307.0       130.0   
1            Buick Skylark 320  15.0        8.0         350.0       165.0   
2           Plymouth Satellite  18.0        8.0         318.0       150.0   
3                AMC Rebel SST  16.0        8.0         304.0       150.0   
4                  Ford Torino  17.0        8.0         302.0       140.0   
..                         ...   ...        ...           ...         ...   
404            Ford Mustang GL  27.0        4.0         140.0        86.0   
405          Volkswagen Pickup  44.0        4.0          97.0        52.0   
406              Dodge Rampage  32.0        4.0         135.0        84.0   
407                Ford Ranger  28.0        4.0         120.0        79.0   
408                 Chevy S-10  31.0        4.0         119.0        82.0   

     Weight  Acceleration  Model  Origin  Based on Weight   
0    3504.0   

In [153]:
#Remove duplicate rows from a DataFrame
Duplicate=Cars.drop_duplicates()
print(Duplicate)

                      Car Name   MPG  Cylinders  Displacement  Horsepower  \
0    Chevrolet Chevelle Malibu  18.0        8.0         307.0       130.0   
1            Buick Skylark 320  15.0        8.0         350.0       165.0   
2           Plymouth Satellite  18.0        8.0         318.0       150.0   
3                AMC Rebel SST  16.0        8.0         304.0       150.0   
4                  Ford Torino  17.0        8.0         302.0       140.0   
..                         ...   ...        ...           ...         ...   
404            Ford Mustang GL  27.0        4.0         140.0        86.0   
405          Volkswagen Pickup  44.0        4.0          97.0        52.0   
406              Dodge Rampage  32.0        4.0         135.0        84.0   
407                Ford Ranger  28.0        4.0         120.0        79.0   
408                 Chevy S-10  31.0        4.0         119.0        82.0   

     Weight  Acceleration  Model  Origin  Based on Weight   
0    3504.0   

In [131]:
# Correlation matrix for a DataFrame
Corr_Matrix = Cars.corr()
print(Corr_Matrix)

                   MPG  Cylinders  Displacement  Horsepower    Weight  \
MPG           1.000000  -0.737080     -0.767657   -0.731210 -0.786019   
Cylinders    -0.737080   1.000000      0.952242    0.824354  0.896523   
Displacement -0.767657   0.952242      1.000000    0.875277  0.933353   
Horsepower   -0.731210   0.824354      0.875277    1.000000  0.841886   
Weight       -0.786019   0.896523      0.933353    0.841886  1.000000   
Acceleration  0.437948  -0.526609     -0.564458   -0.687337 -0.435457   
Model         0.598756  -0.372799     -0.398317   -0.429290 -0.330692   

              Acceleration     Model  
MPG               0.437948  0.598756  
Cylinders        -0.526609 -0.372799  
Displacement     -0.564458 -0.398317  
Horsepower       -0.687337 -0.429290  
Weight           -0.435457 -0.330692  
Acceleration      1.000000  0.315059  
Model             0.315059  1.000000  


In [184]:
Reshape = pd.pivot(Cars, columns=["Origin","Model"])
print(Reshape)

                         Car Name                                           \
Origin                         US Europe Japan       NaN   US Japan Europe   
Model                        70.0   70.0  70.0  NaN 71.0 71.0  71.0   71.0   
0       Chevrolet Chevelle Malibu    NaN   NaN  NaN  NaN  NaN   NaN    NaN   
1               Buick Skylark 320    NaN   NaN  NaN  NaN  NaN   NaN    NaN   
2              Plymouth Satellite    NaN   NaN  NaN  NaN  NaN   NaN    NaN   
3                   Amc Rebel Sst    NaN   NaN  NaN  NaN  NaN   NaN    NaN   
4                     Ford Torino    NaN   NaN  NaN  NaN  NaN   NaN    NaN   
..                            ...    ...   ...  ...  ...  ...   ...    ...   
404                           NaN    NaN   NaN  NaN  NaN  NaN   NaN    NaN   
405                           NaN    NaN   NaN  NaN  NaN  NaN   NaN    NaN   
406                           NaN    NaN   NaN  NaN  NaN  NaN   NaN    NaN   
407                           NaN    NaN   NaN  NaN  NaN  NaN   

In [169]:
#Apply a function to each element in a specific column of a DataFrame
Cars['Car Name'] = Cars['Car Name'].str.title()
print(Cars['Car Name'])


0      Chevrolet Chevelle Malibu
1              Buick Skylark 320
2             Plymouth Satellite
3                  Amc Rebel Sst
4                    Ford Torino
                 ...            
404              Ford Mustang Gl
405            Volkswagen Pickup
406                Dodge Rampage
407                  Ford Ranger
408                   Chevy S-10
Name: Car Name, Length: 409, dtype: object


In [175]:
#Rename the columns of a DataFrame
Cars.rename(columns = {'MPG':'miles per gallon'}, inplace = True)
print(Cars.rename)

<bound method DataFrame.rename of                       Car Name  miles per gallon  Cylinders  Displacement  \
0    Chevrolet Chevelle Malibu              18.0        8.0         307.0   
1            Buick Skylark 320              15.0        8.0         350.0   
2           Plymouth Satellite              18.0        8.0         318.0   
3                Amc Rebel Sst              16.0        8.0         304.0   
4                  Ford Torino              17.0        8.0         302.0   
..                         ...               ...        ...           ...   
404            Ford Mustang Gl              27.0        4.0         140.0   
405          Volkswagen Pickup              44.0        4.0          97.0   
406              Dodge Rampage              32.0        4.0         135.0   
407                Ford Ranger              28.0        4.0         120.0   
408                 Chevy S-10              31.0        4.0         119.0   

     Horsepower  Weight  Acceleration  Mo

In [ ]:
#Save a DataFrame to a CSV file
Cars.to_csv(r'C:/Users/Lenovo/Downloads/Cars(NEW).csv')